@baseUrl = http://127.0.0.1:3000

GET {{baseUrl}}/users/

### Cria um user
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "firstName": "Andrey",
    "lastName": "Goulart",
    "username": "andgoulart",
    "password": "Goulart23#"
}

###
GET {{baseUrl}}/clinical_infos/

###
GET {{baseUrl}}/clinical_infos/users/1

###
GET {{baseUrl}}/clinical_badges/users/1

###
POST {{baseUrl}}/clinical_infos/
Content-Type: application/json

{
    "userId": 1,
    "bloodType": "O+",
    "surgeries": ["colono"],
    "medicines": ["stelara"],
    "chronicDiseases": ["crohn"],
    "emergencyContact": "51992914522"
}

###
GET {{baseUrl}}/clinical_infos/1

###
PATCH {{baseUrl}}/clinical_infos/1
Content-Type: application/json

{
    "userId": 1,
    "bloodType": "O+",
    "allergies": "ibuprofeno",
    "surgeries": "colono",
    "medicines": "stelara",
    "chronicDiseases": "crohn",
    "emergencyContact": "51992914522"
}


###
GET {{baseUrl}}/clinical_badges/

###
POST {{baseUrl}}/clinical_badges/
Content-Type: application/json

{
    "userId": 1,
    "clinicalInfoId": 1,
    "publicPassword": "teste"
}

###
GET {{baseUrl}}/users/1